import { IconType } from "react-icons";
import { FaUmbrellaBeach } from "react-icons/fa6";
import {
  LuArrowRightLeft,
  LuBanknote,
  LuBeer,
  LuBinary,
  LuBrush,
  LuCandy,
  LuCar,
  LuCode,
  LuDumbbell,
  LuGift,
  LuGraduationCap,
  LuHeadphones,
  LuHeart,
  LuHeartPulse,
  LuHome,
  LuLaptop,
  LuMartini,
  LuPartyPopper,
  LuPizza,
  LuPopcorn,
  LuShirt,
  LuShoppingBasket,
  LuSmartphone,
  LuTicket,
} from "react-icons/lu";

export const categoryIcon: Record<string, IconType> = {
  LuHeart,
  LuHeartPulse,
  FaUmbrellaBeach,
  LuHome,
  LuShirt,
  LuShoppingBasket,
  LuPizza,
  LuPartyPopper,
  LuGraduationCap,
  LuCar,
  LuDumbbell,
  LuBanknote,
  LuGift,
  LuArrowRightLeft,
  LuCandy,
  LuBrush,
  LuHeadphones,
  LuTicket,
  LuPopcorn,
  LuBeer,
  LuMartini,
  LuBinary,
  LuCode,
  LuLaptop,
  LuSmartphone,
};
